Fixed buildspec.yaml file;

diff --git a/aws/codebuild/buildspec.yaml b/aws/codebuild/buildspec.yaml
--- a/aws/codebuild/buildspec.yaml
+++ b/aws/codebuild/buildspec.yaml
@@ -37,15 +37,15 @@ phases:
       - echo Checking if request received is from PR $CODEBUILD_WEBHOOK_BASE_REF
       - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain $CODE_ARTIFACT_DOMAIN --domain-owner $CODE_ARTIFACT_OWNER --query authorizationToken --output text`
       - |-
-        if [ ! -z "$CODEBUILD_WEBHOOK_BASE_REF" ]; then CODEBUILD_WEBHOOK_HEAD_REF=$CODEBUILD_WEBHOOK_BASE_REF; fi
+        if [ ! -z "$CODEBUILD_WEBHOOK_BASE_REF" ]; then
+          CODEBUILD_WEBHOOK_HEAD_REF=$CODEBUILD_WEBHOOK_BASE_REF
+        fi
       - |-
         if [ -z "$CODEBUILD_WEBHOOK_HEAD_REF" ] || echo "$CODEBUILD_WEBHOOK_HEAD_REF" | grep -Eq '^(.*\/feature.*)|(.*\/develop)$'; then
           echo "It was triggered by develop/feature branches."
           mvn deploy -B -DskipTests -Dartifactory.url=$ARTIFACTORY_URL -s $SETTINGS_PATH
           echo "Snapshot generated successfully!"
-          exit 0
-      - |-
-        if echo "$CODEBUILD_WEBHOOK_HEAD_REF" | grep -Eq '^(.*\/release.*)|(.*\/qa)$'; then
+        elif echo "$CODEBUILD_WEBHOOK_HEAD_REF" | grep -Eq '^(.*\/release.*)|(.*\/qa)$'; then
           echo "It was triggered by release/qa branches."
           git config --global user.email "cicd@gate39media.com"
           git config --global user.name "CICD Boot Gate 39 Media"
@@ -53,9 +53,10 @@ phases:
           git reset --hard origin/$CODEBUILD_WEBHOOK_HEAD_REF
           mvn release:clean release:prepare release:perform -B -DscmCommentPrefix="[maven-release] [skip ci] " -Darguments="-DskipTests -Dartifactory.url=$ARTIFACTORY_URL" -Drelease.scm.user=$RELEASE_SCM_USER -Drelease.scm.token=$RELEASE_SCM_TOKEN -s $SETTINGS_PATH
           echo "Release was generated successfully!"
-          exit 0
-      - echo "Branch not supported! Aborting..."
-      - exit 1
+        else
+          echo "Branch not supported! Aborting..."
+          exit 1
+        fi
 
 cache:
   paths:
